// Postgres-backed OAuth token storage, encrypted at rest (AES-256-GCM with
// OAUTH_TOKEN_ENCRYPTION_KEY, a 32-byte hex key generated by the installer).
// Decryption happens in-memory on every LLM call. Tokens are never logged
// and never emitted in traces.

import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';
import { eq } from 'drizzle-orm';
import { db, schema } from '../db/client.js';

function key(): Buffer {
  const hex = process.env.OAUTH_TOKEN_ENCRYPTION_KEY;
  if (!hex || hex.length !== 64) {
    throw new Error('OAUTH_TOKEN_ENCRYPTION_KEY must be 32 bytes hex (64 chars) — see .env.example');
  }
  return Buffer.from(hex, 'hex');
}

export function encrypt(plaintext: string): string {
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key(), iv);
  const enc = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${iv.toString('base64')}.${tag.toString('base64')}.${enc.toString('base64')}`;
}

export function decrypt(payload: string): string {
  const [ivB64, tagB64, dataB64] = payload.split('.');
  const decipher = createDecipheriv('aes-256-gcm', key(), Buffer.from(ivB64, 'base64'));
  decipher.setAuthTag(Buffer.from(tagB64, 'base64'));
  return Buffer.concat([
    decipher.update(Buffer.from(dataB64, 'base64')),
    decipher.final(),
  ]).toString('utf8');
}

export interface StoredToken {
  provider: string;
  accessToken: string; // decrypted
  refreshToken?: string; // decrypted
  tokenType: string;
  scope?: string;
  expiresAt?: Date;
}

export async function saveToken(params: {
  provider: string;
  accessToken: string;
  refreshToken?: string;
  tokenType?: string;
  scope?: string;
  expiresAt?: Date;
  connectedByUser: string;
}): Promise<void> {
  await db
    .insert(schema.oauthTokens)
    .values({
      provider: params.provider,
      accessToken: encrypt(params.accessToken),
      refreshToken: params.refreshToken ? encrypt(params.refreshToken) : null,
      tokenType: params.tokenType ?? 'Bearer',
      scope: params.scope ?? null,
      expiresAt: params.expiresAt ?? null,
      connectedByUser: params.connectedByUser,
      refreshedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: schema.oauthTokens.provider,
      set: {
        accessToken: encrypt(params.accessToken),
        refreshToken: params.refreshToken ? encrypt(params.refreshToken) : null,
        tokenType: params.tokenType ?? 'Bearer',
        scope: params.scope ?? null,
        expiresAt: params.expiresAt ?? null,
        refreshedAt: new Date(),
      },
    });
}

export async function getToken(provider: string): Promise<StoredToken | null> {
  const [row] = await db
    .select()
    .from(schema.oauthTokens)
    .where(eq(schema.oauthTokens.provider, provider));
  if (!row) return null;
  return {
    provider: row.provider,
    accessToken: decrypt(row.accessToken),
    refreshToken: row.refreshToken ? decrypt(row.refreshToken) : undefined,
    tokenType: row.tokenType,
    scope: row.scope ?? undefined,
    expiresAt: row.expiresAt ?? undefined,
  };
}

export async function deleteToken(provider: string): Promise<void> {
  await db.delete(schema.oauthTokens).where(eq(schema.oauthTokens.provider, provider));
}
