// Postgres-backed OAuth token storage, encrypted at rest (AES-256-GCM with
// OAUTH_TOKEN_ENCRYPTION_KEY, a 32-byte hex key generated by the installer).
// Decryption happens in-memory on every LLM call. Tokens are never logged
// and never emitted in traces.

import { eq } from 'drizzle-orm';
import { db, schema } from '../db/client.js';
import { decrypt, encrypt } from '../security/token-envelope.js';

export { decrypt, encrypt };

export interface StoredToken {
  provider: string;
  accessToken: string; // decrypted
  refreshToken?: string; // decrypted
  tokenType: string;
  scope?: string;
  expiresAt?: Date;
}

export async function saveToken(params: {
  provider: string;
  accessToken: string;
  refreshToken?: string;
  tokenType?: string;
  scope?: string;
  expiresAt?: Date;
  connectedByUser: string;
}): Promise<void> {
  await db
    .insert(schema.oauthTokens)
    .values({
      provider: params.provider,
      accessToken: encrypt(params.accessToken),
      refreshToken: params.refreshToken ? encrypt(params.refreshToken) : null,
      tokenType: params.tokenType ?? 'Bearer',
      scope: params.scope ?? null,
      expiresAt: params.expiresAt ?? null,
      connectedByUser: params.connectedByUser,
      refreshedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: schema.oauthTokens.provider,
      set: {
        accessToken: encrypt(params.accessToken),
        refreshToken: params.refreshToken ? encrypt(params.refreshToken) : null,
        tokenType: params.tokenType ?? 'Bearer',
        scope: params.scope ?? null,
        expiresAt: params.expiresAt ?? null,
        refreshedAt: new Date(),
      },
    });
}

export async function getToken(provider: string): Promise<StoredToken | null> {
  const [row] = await db
    .select()
    .from(schema.oauthTokens)
    .where(eq(schema.oauthTokens.provider, provider));
  if (!row) return null;
  return {
    provider: row.provider,
    accessToken: decrypt(row.accessToken),
    refreshToken: row.refreshToken ? decrypt(row.refreshToken) : undefined,
    tokenType: row.tokenType,
    scope: row.scope ?? undefined,
    expiresAt: row.expiresAt ?? undefined,
  };
}

export async function deleteToken(provider: string): Promise<void> {
  await db.delete(schema.oauthTokens).where(eq(schema.oauthTokens.provider, provider));
}
